# Generated by Django 4.2.15 on 2025-03-27 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('video_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('language', models.CharField(default='hi', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['video_id'], name='api_transcr_video_i_3a6b19_idx'),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['user_id', 'created_at'], name='api_transcr_user_id_2a6b19_idx'),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['user_id', 'is_favorite'], name='api_transcr_user_id_1a6b19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transcript',
            unique_together={('user_id', 'video_id')},
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('novice', 'Novice'), ('mcq', 'Multiple Choice'), ('fill_blanks', 'Fill in the Blanks')], max_length=20)),
                ('question_text', models.TextField()),
                ('answer', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('transcript', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='questions', to='api.transcript')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['transcript', 'question_type'], name='api_questio_transcr_1a6b19_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['transcript', 'is_favorite'], name='api_questio_transcr_2a6b19_idx'),
        ),
    ]
