# Generated by Django 4.2.15 on 2025-03-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transcript',
            name='api_transcr_user_id_a9c67d_idx',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='is_favorite',
        ),
        migrations.AlterField(
            model_name='transcript',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
