# Generated by Django 4.2.15 on 2025-03-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_transcript_api_transcr_user_id_a9c67d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['user', 'is_favorite'], name='api_transcr_user_id_a9c67d_idx'),
        ),
    ]
