# Generated by Django 4.2.15 on 2025-03-30 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transcript_is_favorite_alter_transcript_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('novice', 'Novice'), ('mcq', 'Multiple Choice'), ('fill_blanks', 'Fill in the Blanks')], max_length=20)),
                ('question_text', models.TextField()),
                ('answer', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.transcript')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transcript', 'question_type'], name='api_questio_transcr_69c251_idx'), models.Index(fields=['transcript', 'is_favorite'], name='api_questio_transcr_e35646_idx')],
            },
        ),
    ]
