# Generated by Django 4.2.15 on 2025-03-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
