# Generated by Django 4.2.15 on 2025-03-31 06:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_question_attempts_question_correct_attempts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transcript',
            unique_together={('user', 'video_id')},
        ),
    ]
